### PR TITLE
Protocol 1.2.6

### PR DESCRIPTION
**Pull request by HoverEpic**
Update protocol for client compatibility.

### CODE REVIEW

**Review by DefinitlyEvil — COMMENTED** [review]
Any packet structural changes?

**Comment by HoverEpic** [comment]
I haven't seen any changes in Minet doc so i think there is no changes.

**Comment by DefinitlyEvil** [comment]
Why they change protocol number tho. :/

**Review by DefinitlyEvil — APPROVED** [review]

**Comment by HoverEpic** [comment]
They change each time to force servers to update i think ><

**Comment by DefinitlyEvil** [comment]
Lol they don't care theirs party implementations

**Comment by lukeeey** [comment]
They update the prorocol number so you can tell the difference between versions...

**Pull request merged**
