### PR TITLE
Some bedrock stuff

### PR DESCRIPTION
**Pull request by EOT3000**
A work in progress, i'll continue making the methods work (if you see that the method returns Boolean, its not finished).

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
Looks cool!

**Comment by lukeeey** [comment]
Hey @DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
hi @lukeeey ;)

**Comment by EOT3000** [comment]
I'm an Idiot! I forgot to update pom.xml!

**Comment by DefinitlyEvil** [comment]
@EOT3000 hi did you do tests on them? if yes, I'll merge them.

**Comment by SupremeMortal** [comment]
The build failed so I guess it isn't ready?

**Comment by EOT3000** [comment]
no, not ready, also, I didn't test

**Pull request closed without merging**
