### PR TITLE
Put the steps on different lines

### PR DESCRIPTION
**Pull request by SirFaizdat**
Allows for better readability.

### CODE REVIEW

**Comment by TekkitCommando** [comment]
Hmmm.

**Comment by TekkitCommando** [comment]
Yeah ok, PR's fine. @DefinitlyEvil remember to git pull.

**Comment by DefinitlyEvil** [comment]
And `--rebase` lol.

**Comment by TekkitCommando** [comment]
xD

**Comment by TheDiamondYT1** [comment]
My fault I rushed this file

**Comment by TekkitCommando** [comment]
It's cool.

**Pull request merged**
