### PR TITLE
Fix crashing 0.15 on unknown block

### PR DESCRIPTION
**Pull request by Encritary**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Whats id 248?

**Comment by TheDiamondYT1** [comment]
If you wanna make more commits add more than one features in the PR

**Comment by Encritary** [comment]
@TheDiamondYT1 Update block. It doesn't crashs, but unknown ids crashs the game.

**Comment by TheDiamondYT1** [comment]
Im gonna invite you as a collaborator. Dont spam commits please

**Comment by TheDiamondYT1** [comment]
You have direct push access to the repo now

**Pull request merged**
