### PR TITLE
Begin to merge robotman3000/master into DragonetMC/refactor

### PR DESCRIPTION
**Pull request by robotman3000**
I'm looking to merge my code into the refactor branch and begin developing here, instead of my fork. There is just the issue of what to do with the [Update Translators](https://github.com/robotman3000/DragonProxy/pull/19) PR that I have from @DaMatrix. My thought is to close his PR to my fork, then merge this PR into the refactor branch, and finally have @DaMatrix resubmit his PR for this repo instead. @DragonetMC/developers What do you think of this plan?

### CODE REVIEW

**Comment by robotman3000** [comment]
@DragonetMC/developers I also think that we should create a wiki here to document the intricacies and specifics (more like bugs to work around) of the MCPE Protocol.

**Comment by DaMatrix** [comment]
I can resubmit the pull here. Want me to do that?

**Comment by TheDiamondYT1** [comment]
@robotman3000 The wiki is a good idea, I was planning to make one on my website aswell.

As for this PR, I'm current at school so...yeah..

Bump.

**Comment by robotman3000** [comment]
@DaMatrix Yes go ahead and submit the PR and then when it is finished and after _this_ PR is merged then yours can also be merged

@TheDiamondYT1 So is it all systems go to merge this PR?

**Comment by robotman3000** [comment]
@TheDiamondYT1 Thanks, I will go ahead and start the wiki in this repo so that we can let people begin work on it

**Comment by robotman3000** [comment]
@TheDiamondYT1 One problem with starting the wiki myself... I can't find the settings tab. What permissions level is needed for that?

**Comment by robotman3000** [comment]
@DragonetMC/developers Should I go ahead and merge this?

**Pull request merged**
