### PR TITLE
Uploaded Pocket Edition Protocol IDs

### PR DESCRIPTION
**Pull request by RednedEpic**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Umm...this is not even a java class...

**Comment by TekkitCommando** [comment]
Well it has a class identifier and a name so it's a class lol.

**Comment by TheDiamondYT1** [comment]
@TekkitCommando Lol no. He needs to recreate the maven project.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 whoops xD my bad sry

**Comment by jrodr10** [comment]
No its a class lol, @TheDiamondYT1

**Comment by TheDiamondYT1** [comment]
@jrodr10 No, it is not

**Comment by RednedEpic** [comment]
My bad, I fixed it.

**Comment by TheDiamondYT1** [comment]
Its kinda dead... I might be able to work on it soon tho ;)

**Pull request closed without merging**
