### PR TITLE
Fix null causing disconnect reasons not appear & ping passthrough

### PR DESCRIPTION
**Pull request by Xayanix**

### CODE REVIEW

**Comment by Xayanix** [comment]
Added additional commit for ping passthrough (like in bungeecord). It's optional, if u accept it remember to commit config.yml too.

**Comment by HoverEpic** [comment]
Thank you for this one, i was trying to understand yesterday why the disconnect isn't working.

**Comment by HoverEpic** [comment]
The ping_passthrough seems to be buggy, i have weird things in debug mode. i'll temporary disable this.

**Comment by Xayanix** [comment]
@HoverEpic I was testing it and it was working fine on android.
screenshot_20180315-164817

However, didn't notice it before but in DragonProxy.java there should be check if passthrough is enabled before starting PingThread.

```
if(this.getConfig().ping_passthrough)
      new PingThread();

**Comment by HoverEpic** [comment]
I'm on it.

**Comment by HoverEpic** [comment]
and i have a lot of threads created every seconds...

**Comment by Xayanix** [comment]
That's weird, looks like it's working pretty well on my side.

**Comment by HoverEpic** [comment]
it's working, but MCProtocolLib seems starting 20 threads for each ping. I'm maging ping disable by default. The system should be probably improved later.

**Pull request merged**
