### PR TITLE
Implement proper logging

### PR DESCRIPTION
**Pull request by BrainStone**
This should greatly improve the logging.

Includes colored logs, async file log and automatic log rolling.

Please test before merging. I'm currently not able to check if it works.

### CODE REVIEW

**Comment by HoverEpic** [comment]
Failed to push on your branch >< https://github.com/DragonetMC/DragonProxy/commits/BrainStone-master

**Review by HoverEpic — APPROVED** [review]
With my latest changes on https://github.com/DragonetMC/DragonProxy/commits/BrainStone-master should be ok

**Comment by sgdc3** [comment]
why log4j? slf4j + logback has become the standard nowadays

**Comment by HoverEpic** [comment]
I have reverted changes, the logger wasn't able to start outside an IDE.

**Comment by BrainStone** [comment]
@sgdc3 because that's what I'm familiar with. And it works well. Most of the time :sweat_smile:

**Comment by BrainStone** [comment]
I'm also trying to get it working again!

**Comment by sgdc3** [comment]
Please keep using slf4j and logback, as this is what the project is currently using. @BrainStone

**Comment by BrainStone** [comment]
It is? Only thing I saw related to slf4j is the NOP-logger

**Comment by sgdc3** [comment]
I did a pr some while ago, now we use logback as logger

**Comment by sgdc3** [comment]
https://github.com/DragonetMC/DragonProxy/blob/master/proxy/pom.xml#L123

**Comment by BrainStone** [comment]
Ah ok. has it been merged into the master branch? Because the latest dev build still doesn't create any logs.

**Comment by BrainStone** [comment]
Nevermind. I see it.

**Comment by HoverEpic** [comment]
Sorry @BrainStone,  but you did not respond after i merged your PR into master and the proxy was not able to start outside developement environement, so i reverted your changes. And few days later, @sgdc3 implements slf4j base and it works. If you want to improve the system, you can.

**Pull request merged**
