### PR TITLE
Dependencies cleanup

### PR DESCRIPTION
**Pull request by sgdc3**
- Remove unused dependencies
- Update dependencies
- Minor code cleanup
- General pom file cleanup

### CODE REVIEW

**Comment by sgdc3** [comment]
@lukeeey we should move all the nukkit's sources to a separate package,

**Comment by lukeeey** [comment]
Feel free to do it if you want, but can we keep the main chunk class (the one that creates the packet) in the main package? I plan to remove a lot of the nukkit code from that class when tiles are implemented properly

**Comment by sgdc3** [comment]
Oh ok, what about this pr?

**Comment by sgdc3** [comment]
@lukeeey bump

**Comment by lukeeey** [comment]
Sorry ive been busy recently and the times ive been at my laptop ive been doing college work

**Comment by lukeeey** [comment]
Merge it if it works i trust your judgement

**Review by lukeeey — APPROVED** [review]

**Pull request merged**
