### PR TITLE
fix actionbar text displayed in chat and chat issue with servers

### PR DESCRIPTION
**Pull request by francois76**
A fix to set the actionbar text sent with chat packet in the actionbar

I've also fixed an issue with some messages that are sent in the text field of a Message object instead of being sent as the message itself.

These two fixes can be seen on play.epicube.fr

### CODE REVIEW

**Comment by lukeeey** [comment]
Fix your indentation and brace style to be the same as all the other functions...

**Review by ethsmith — DISMISSED** [review]
Please follow the same code style.

**Comment by francois76** [comment]
code format should be ok, now. I've also fix an issue with messages starting with "{"

**Comment by lukeeey** [comment]
If someone could just test this then that would be great 

@DragonetMC/developers

**Review by lukeeey — APPROVED** [review]
I can't really test right now but it looks alright

**Review by DefinitlyEvil — APPROVED** [review]

**Pull request merged**
