### PR TITLE
Plugin and Event API

### PR DESCRIPTION
**Pull request by tr7zw**
Adds the https://github.com/decebals/pf4j plugin api to load .jar plugins located in the plugins folder.
Also adding an Event system that should feel for Spigot developers like home.

### CODE REVIEW

**Comment by lukeeey** [comment]
Oh god no.

No.

Not additional libraries.

Ughhhhh.

Kill me.

---

I'm tempted to close this because i wanted to make it like https://github.com/voxelwind/voxelwind when the proxy had become more stable, but it looks like you've done alot of work and idk what @HoverEpic wants

**Comment by lukeeey** [comment]
Maybe it wont be that bad though

**Comment by HoverEpic** [comment]
I think it's OK @lukeeey , i asked for that feature, and it's done. Libraries are not a real problem.

**Comment by tr7zw** [comment]
@lukeeey I don't know what exactly the problem with libraries is, all it does is save work to rewrite all the classloaders and stuff. I mean, I won't stop you from writing the plugin loading from scratch like voxelwind^^

**Comment by lukeeey** [comment]
Nah its fine im just picky 😂

But im not running this project.

**Comment by lukeeey** [comment]
Why?

**Comment by HoverEpic** [comment]
I ducked the branch wit a ducked master sync

**Comment by sgdc3** [comment]
@HoverEpic I'll reduce the amount of dependencies soon

**Pull request closed without merging**
