### PR TITLE
Create ja_JP.lang

### PR DESCRIPTION
**Pull request by haniokasai**
cre8 japanese langfile!

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
thx this file is missing `broadcast_title`, would u mind adding this for us? thanks. ;)

**Comment by DefinitlyEvil** [comment]
Sorry I didn't see that, but I do now. xD Thanks for contributing. ;)

**Comment by haniokasai** [comment]
This okay?

**Comment by DefinitlyEvil** [comment]
Yep, thanks. ;)

**Pull request merged**
