### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by EOT3000**

### CODE REVIEW

**Comment by lukeeey** [comment]
Jesus christ what have you done to the formatting lol

Also why didnt you just add this to your other PR?

**Comment by EOT3000** [comment]
This is my 3rd time using GitHub, also, I copyed from this pom.xml, pasted in my pom.xml, and added the repository and dependency for nukkitx

**Comment by EOT3000** [comment]
I copyed because my pom.xml in my project on my computer is outdated, so there were some things that had to be updated.

**Comment by EOT3000** [comment]
lukeey is right, I should have commited to my other pull request

**Pull request closed without merging**
