### PR TITLE
Fix translators

### PR DESCRIPTION
**Pull request by DaMatrix**
A continuation of [this](https://github.com/robotman3000/DragonProxy/pull/19)

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
there are conflicts :(

**Comment by robotman3000** [comment]
@DefinitlyEvil I have used the command line to resolve the conflicts already, I was just waiting for the OK the merge before I pushed the fixes.

**Comment by robotman3000** [comment]
@DefinitlyEvil Could you enable the wiki for this repo? I don't have the right permissions to start it.

**Comment by DaMatrix** [comment]
Is there like a Discord or an IRC or something that we can use for communication?

**Comment by yangm97** [comment]
I would suggest using matrix.org, since a matrix room can be accessed from IRC, gitter, Telegram and other protocols using bridges. Even discord can be bridged.

**Comment by DaMatrix** [comment]
The thing with matrix is that (as far as I know) one would have to host the server by oneself which isn't needed on Discord D:

**Comment by DaMatrix** [comment]
So so far this PR allows a 1.0.3 client to connect to an offline mode pc server and recieve chat, as well as pc <=> pc and pe <=> pe passthrough modes. I think the next big step would be handling BatchPackets as we don't seem to get any other types from the client after login

**Comment by yangm97** [comment]
You can use matrix.org servers to create an account and a room. Try using http://riot.im. Also they have public (“official”) IRC, gitter and slack bridges, someone made a public telegram bridge and hosted it, though other bridges like discord and xmpp are WIP and aren’t hosted publicly afaik.

**Comment by DaMatrix** [comment]
If somebody with write access can revert 0ec3220fe6a895704ec103703b06735c2b5ab4cd merge conflicts would be resolved

**Comment by robotman3000** [comment]
@DaMatrix Yes, your plan about batch packets is good. I was actually do that very thing once we got the PR's figured out. I was thinking to put static methods to handle packet encapsulation, batching, and conversion to and from RakNetPackets and the sul packet classes in a class called `RakNetProtocol` or some similar name. It would allow us to move the packet parsing out of the translator system and back into the ProtocolAdapters, leaving just the translating in the translator system.

**Comment by robotman3000** [comment]
@DaMatrix @DragonetMC/developers Should I merge this PR too?

**Comment by DefinitlyEvil** [comment]
@robotman3000 yea since you spent loads of time doing it

**Pull request merged**
