### PR TITLE
Mistake; Pull changes from master

### PR DESCRIPTION
**Pull request by robotman3000**

### CODE REVIEW

**Comment by robotman3000** [comment]
Sorry, I made the request in reverse.

**Comment by DefinitlyEvil** [comment]
@robotman3000 You can take over the project if you want ;) no need to fork it

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I invited him to the organisation in the "developers" team

**Comment by MrPowerGamerBR** [comment]
Probably he was going to pull the changes from here to his repo

**Comment by MrPowerGamerBR** [comment]
Anyway, cool to see someone trying to update DragonProxy. 😄 

Maybe I will try helping later...

**Comment by MrPowerGamerBR** [comment]
Now I tested his fork, and...

Well, it isn't done yet (chunk aren't sent to the client), but it at least does work, so...

**Comment by robotman3000** [comment]
Yes, that was my plan but then I realized that the only commit I didn't have was an update to the readme. So I just left it.

**Comment by inxomnyaa** [comment]
Doesnt matter xD

**Comment by TheDiamondYT1** [comment]
@robotman3000 Well you have direct access to master, so knock yourself out.

**Comment by robotman3000** [comment]
I'm not sure where to put this so I will ask here. Could I have the source code for the cls authentication server?

**Comment by TheDiamondYT1** [comment]
Its a few simple php scriprs hich contain mysql password

**Comment by TheDiamondYT1** [comment]
I cant type

**Comment by DefinitlyEvil** [comment]
@robotman3000 don't afraid to make mistakes lol, if u check out my commits you'll find a lot of them like 'fix again' or even 'try to fix the 3rd time' haha.

**Comment by DefinitlyEvil** [comment]
@robotman3000 @TheDiamondYT1 don't worry the CLS stuff, it should be working as long as Mojang doesn't change the login scheme and I should be able to maintain those hehe

**Comment by wilsondc15** [comment]
@robotman3000 @DefinitlyEvil @TheDiamondYT1 Robotman, your drone.io links are not working, I do not have that much technical experience, could you please provide me with a compiled, ready-to-go build of your fork of DragonProxy? If Robotman cannot, could someone else here please send me this? I would really appreciate it, thank you!

**Comment by MrPowerGamerBR** [comment]
@wilsondc15 keep in mind that @robotman3000's fork isn't done, so the only thing you can do is join the proxy and... that's it, the chunk translator is broken at the moment so there isn't a lot of things to do.

http://198.50.225.188/dragonproxy-0.0.6-preR1.jar

**Comment by wilsondc15** [comment]
@MrPowerGamerBR Thank you for the quick response! I really hope that someone will fix the chunk translator!

**Comment by TheDiamondYT1** [comment]
@robotman3000 Please make a PR to the redactor branch of this repo! Then you can continue committing directly to this repi

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 there isn't any reason to merge his changes yet, it still doesn't work.

Maybe he will merge when he figures out why the fuck chunks aren't working.

**Comment by TheDiamondYT1** [comment]
Yes but the point of it was so he can just commit directly to this repo

**Comment by TheDiamondYT1** [comment]
I'm gonna do a bit of repo cleanup

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 also, after thinking about a little bit, I think implementing commands properly in DragonProxy (or any related projects) will be impossible due to the new changes in MCPE.

Now you need to send a packet with all the available commands the player can execute... and that's impossible to do with only a proxy.

Unless if you change the "/" to something else, but that's just a bad workaround, the only way to fix it is by using a plugin. (which ProtocolSupport may fit for this... however progress in the new mcpe branch for ProtocolSupport hasn't started yet, so...)

**Comment by TheDiamondYT1** [comment]
Commands arent the biggest problem right now

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 yeah, but that's what I was thinking when I was trying to create a MCPE proxy.

The "huge" issue are chunks... those damn chunks, why they needed to change the chunk packet! Oh... I forgot, due to the 256 height change.

I will probably tackle at DragonProxy again later, but when I tried debugging the chunk issue I couldn't get anywhere. (and I'm waiting to see what is going to happen with ProtocolSupport's mcpe branch and Nukkit)

**Comment by MrPowerGamerBR** [comment]
It also doesn't help that MCPE doesn't have any kind of logging, of it doesn't work and you don't know why, or it crashes and you don't know why, or it just works.

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR actually proxy commands didn't working at all times xD

**Comment by DefinitlyEvil** [comment]
okay peeps u rly ignored me :(

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil I'm talking about server side commands, not proxy commands.

You can't magically figure out all the commands that exists in the server, and that's a issue since you need to know all the commands in the server to send the "AvailableCommandsPacket" to the client with all the available commands on the server.

**Comment by inxomnyaa** [comment]
Commands are "easy". I could try to do it. Please pr the stuff to the 1.0 branch

**Pull request closed without merging**
