### PR TITLE
Query the PC Server to get the online/max players.

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
It should be = not :

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy whoops

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy fixed.

**Comment by MrPowerGamerBR** [comment]
I'm uploading a screenshot showing the commit, wait a second.

**Comment by MrPowerGamerBR** [comment]
screenshot_20160116-121725

Fancy, isn't it?

If DragonProxy becomes more stable, maybe I will create a official server :+1: 

(Also, why the nide8.com (one of the official Servers) never connects?)

**Pull request merged**
