### PR TITLE
add WIP support for chat translation

### PR DESCRIPTION
**Pull request by francois76**
WIP system for translation message with lot of workarounds. I will maybe make it better later with a specific behaviour for each translation key.
Also a quick fix for the chat in some cases and blank classes for the bossbar support.

### CODE REVIEW

**Comment by HoverEpic** [comment]
Nice, can i merge it now? or you probably prefer to wait it's finished?

**Comment by lukeeey** [comment]
I hate how everyone uses different styles like using this for function calls 😂

**Comment by francois76** [comment]
Yes you can, it may be long to make it working perfectly.

**Comment by HoverEpic** [comment]
Ok, lets merge, i'll fix formating too

**Comment by lukeeey** [comment]
other projects dont seem to have so many people messing up formatting though

**Pull request merged**
