### PR TITLE
Fix EntityEffectPacketTranslator

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by HoverEpic** [comment]
Effect ids are the same on Java and Bedrock? If yes that's pretty cool

**Comment by DefinitlyEvil** [comment]
nope, mostly are the same but some particular ones aren't. :/

**Comment by DefinitlyEvil** [comment]
oh shiet it was effext IDs lol nvm i.thought it was for block IDs.

**Comment by HoverEpic** [comment]
merged into indev branch

**Comment by Creeperface01** [comment]
WTF,

**Comment by Creeperface01** [comment]
I fixed block metadata. Now I don't understand anything. IntelliJ is bugged somehow and changed files randomly disappear from the list so probably they weren't be commited or idk..

**Comment by DefinitlyEvil** [comment]
i usually just fully recompile and run using a terminal.

**Pull request closed without merging**
