### PR TITLE
Slab block data fix

### PR DESCRIPTION
**Pull request by ApocalypsjeNL**
Slab block data fix, because some slabs are incorrectly shown on PE side

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
make sure to remove those `System.out.println();` things before merging. :P

**Comment by ApocalypsjeNL** [comment]
Yeah xD

**Comment by HoverEpic** [comment]
Can you make a list of broken datas blocks, I'll take a look if I have time.

**Comment by ApocalypsjeNL** [comment]
Sure, I'll create all blocks in my world and test them

**Comment by HoverEpic** [comment]
Why not use the debug world from the client?

**Comment by ApocalypsjeNL** [comment]
It's broken on servers, https://www.spigotmc.org/threads/load-debug-world-in-server.249691/

**Comment by HoverEpic** [comment]
I'm actually using Qmagnet 1.12.2 test map, there is probably another map with blocks statrs for testing.

**Review by HoverEpic — CHANGES_REQUESTED** [review]
Check your colums indentation, use 4 spaces instead of \t.

**Comment by lukeeey** [comment]
The spacing is completely messed up https://raw.githubusercontent.com/ApocalypsjeNL/DragonProxy/f0b7ad3369fb7406a9f5d77b237dd9f695b86fa3/src/main/java/org/dragonet/proxy/network/translator/itemsblocks/SlabDataTranslator.java

EDIT: ah thats better

**Comment by ApocalypsjeNL** [comment]
https://raw.githubusercontent.com/ApocalypsjeNL/DragonProxy/172d65ec6779af15137eea6175cc003e5ec5076c/src/main/java/org/dragonet/proxy/network/translator/itemsblocks/SlabDataTranslator.java It should be fixed

**Review by HoverEpic — APPROVED** [review]

**Review by lukeeey — APPROVED** [review]

**Comment by lukeeey** [comment]
**Don't merge yet as it's still incomplete**

**Comment by lukeeey** [comment]
Oh wow, thanks for reformatting :D

**Comment by ApocalypsjeNL** [comment]
@lukeeey Maybe you want to merge this and call it slab fixes, need to reorganise my github repo because I didn't start working in branches for every fix xD

**Pull request merged**
