### PR TITLE
ko_KR entry update

### PR DESCRIPTION
**Pull request by KangYui**
Update ko_KR with new entry!
--Secret: My One Wish is get collaborators..--

### CODE REVIEW

**Comment by KangYui** [comment]
And if you need more lang entry, contact kangyui851@gmail.com. i am everyday online!

**Comment by DefinitlyEvil** [comment]
Thanks for contributing but you have to rename it to `ko_KR.lang`. ;) Thx.

**Comment by KangYui** [comment]
OK Wait!

**Comment by KangYui** [comment]
Like this?

**Comment by DefinitlyEvil** [comment]
Yep! ;)

**Pull request merged**
