### PR TITLE
Fixed console errors

### LINKED ISSUE #137: Error while executing command console flood
kepkivagas

### PR DESCRIPTION
**Pull request by ApocalypsjeNL**
Fixes #137 which caused the MultiCraft, Intellij and other hosted consoles to freak out

### CODE REVIEW

**Review by HoverEpic — APPROVED** [review]
Looks good !

**Review by DefinitlyEvil — COMMENTED** [review]
Ouch, bad code. You shouldn't create a new Scanner every time you read a line!

**Comment by HoverEpic** [comment]
Ok, this need some improvments, but there is no spamming console errors at all =)

**Comment by ApocalypsjeNL** [comment]
Gonna improve the console system a bit more yes, but this is a quick fix to remove the spamming issue

**Comment by lukeeey** [comment]
Try something like this
```java
try {
    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
    while (!proxy.isShuttingDown()) {
        System.out.print(">");
        command = reader.readLine();

	if (command == null || command.trim().length() == 0) {
	    continue;
	}

        proxy.getCommandRegister().callCommand(command);
    }
} catch (Exception ex) {
    logger.severe("Error while executing command: " + ex);
    ex.printStackTrace();
} finally {
    if(reader != null) {
        try {
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**Pull request merged**
