### PR TITLE
Another work on entities

### PR DESCRIPTION
**Pull request by HoverEpic**
Named entities now display the good name !
Skins aren't gonna work for now, i need to create a skin cache.
Metadatas are not functional for now but i'w working on it.

Client permissions are now "MEMBER" and connected players are vieable from pause menu.

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
Oh my God you are amazing, I have to apologize that I am not active on DP these days.

**Comment by HoverEpic** [comment]
No problem  ^^
(I'm currently on entity metadatas translator, and i'ts a real pain ><)

**Comment by HoverEpic** [comment]
Entities meta working (only sneak tested but i only want to test the translator).

**Comment by yoft** [comment]
Awesome work HoverEpic!

**Comment by yoft** [comment]
Will there be another build uploaded soon?

**Comment by HoverEpic** [comment]
Pull requests have to be accepted before building a new version.

**Review by DefinitlyEvil — APPROVED** [review]
this looks legit so let's merge it :P

**Comment by HoverEpic** [comment]
Let's merge the others ^^

**Comment by DefinitlyEvil** [comment]
you can just work directly on master repo, you know :P I invited you to the dev team.

**Comment by HoverEpic** [comment]
Ok,let's go ^^

**Pull request merged**
