### PR TITLE
More details about protocol

### PR DESCRIPTION
**Pull request by U-siro**

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
:/ `All servers utilize standarn Minecraft protocol should work. ` simple and easy

**Comment by DefinitlyEvil** [comment]
lol

**Comment by Redned235** [comment]
`All servers that utilize the standard Minecraft protocol should work. ` - there, makes a bit more since

**Comment by lukeeey** [comment]
Since there has been README updates and this doesn't make sense anyway, i'm gonna go ahead and close this.

**Pull request closed without merging**
