### PR TITLE
Armors are now visible

### PR DESCRIPTION
**Pull request by francois76**
Armors are now visible on other entities.
(entitycache hasn't been changed, I've just recovered it after having tried Something)

### CODE REVIEW

**Comment by DefinitlyEvil** [comment]
could you pls re-make your PR into one commit only?

**Review by DefinitlyEvil — CHANGES_REQUESTED** [review]
one commit per PR

**Comment by HoverEpic** [comment]
Or avoid commiting an entire file =)

**Comment by lukeeey** [comment]
@DefinitelyEvil 1 commit per PR is stupid. Just hit the squash and merge button.

**Comment by DefinitlyEvil** [comment]
@lukeeey just wanna avoid useless commits even with squashing.

**Comment by lukeeey** [comment]
Do you know what squashing does? It removes those useless commits and makes it into one single good commit

**Comment by DefinitlyEvil** [comment]
@lukeeey kk xD i thought it was just for hard combing. :P

**Pull request closed without merging**
