### PR TITLE
Small changes.

### PR DESCRIPTION
**Pull request by TheMasterBlaster**
Added Linux as supported Server, Added Vanilla and LilyPad as supported Remote Servers, Small changes.

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
It's connecting to MojangAB, not connecting to MojangAB Server.

And we don't need to list every server software that exists.

**Comment by mastercoms** [comment]
I would recommend merging Bukkit and Spigot together, by saying Bukkit-based.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster And PC = a platform which includes windows and linux.

**Comment by mastercoms** [comment]
Technically, PC includes Mac as well.

**Comment by TheMasterBlaster** [comment]
@mastercoms Windows 10 Edition does not work exactly the same as Pocket Edition. Some features DragonProxy has works on PE but not the Win 10 Edition.

**Comment by TekkitCommando** [comment]
@RandomAltThingy why do you keep closing this?

**Comment by RandomAltThingy** [comment]
@TekkitCommando Well it aint needed

**Comment by TekkitCommando** [comment]
@RandomAltThingy sorry xD I didn't read the messages just saw you and mastercoms opening and closing it.

**Pull request closed without merging**
