### PR TITLE
1.0.7

### PR DESCRIPTION
**Pull request by DelxHQ**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Why close

**Comment by ghost** [comment]
is it working

**Comment by DelxHQ** [comment]
i have not tested it yet, i cba compiling. maybe i should before this gets merged...

**Comment by DefinitlyEvil** [comment]
you can take over this project if you like ;)

**Comment by TheDiamondYT1** [comment]
So im gonna be a dick because the whole codebase needs re-doing. Sorry.

**Pull request closed without merging**
