### PR TITLE
Merge the improved networking system to the refactor branch

### PR DESCRIPTION
**Pull request by robotman3000**
The new networking classes are in org.dragonet.proxy.network.adapter. UpstreamSession has become ClientConnection, and the networking part of UpstreamSession and DownstreamSession has been moved into the client and server protocol adapters. DownstreamSession has ceased to exist. The PE networking system no longer uses Nukkit in favor of JRakNet and has been rewritten.

The proxy is now in need of packet classes for the PE networking system. I think we can use sel-project/sel-utils to get these classes either by hand, code generation from the json protocol docs, or using the existing java classes by making a fork and modifying them as needed.

### CODE REVIEW

**Comment by ethsmith** [comment]
@robotman3000 Are you going to keep adding on this PR or are you wanting a review and merge?

Edit: Nvm I didn't see your member tag before.

**Comment by ethsmith** [comment]
@robotman3000  If you are wanting a review we will leave that to @TheDiamondYT1 since DefinitlyEvil and I are working on some other projects.

**Review by TheDiamondYT1 — APPROVED** [review]
Well i cant test as have no access to a computer rright now, but i trust that this works (to an extent).  So i will merge it .

**Comment by robotman3000** [comment]
I have done minimal testing but it's still somewhat broken

**Comment by TheDiamondYT1** [comment]
Well anything is better than the current state

**Pull request merged**
