### PR TITLE
[WIP] Remove JsonSimple, pom cleanup

### PR DESCRIPTION
**Pull request by sgdc3**
Still need to add the logback config

### CODE REVIEW

**Comment by ethsmith** [comment]
Why the change to gson?

**Comment by sgdc3** [comment]
Because it was already included, why use 2 different libraries?

**Comment by sgdc3** [comment]
gson + json + json-simple :/

**Comment by sgdc3** [comment]
I didn't change to gson, gson was already there, i just replaced the usages of json and jsonsimple

**Comment by sgdc3** [comment]
That makes the final jar size smaller, as we have to shade less dependencies

**Comment by HoverEpic** [comment]
I made that, thanks for fixing.

**Comment by lukeeey** [comment]
Bump

**Comment by sgdc3** [comment]
need time to work on that, currently very busy with work :(

**Comment by lukeeey** [comment]
What exactly is the issue and i can fix it. What is the "logback config"?

**Comment by sgdc3** [comment]
atm all the log levels are shown, a logback filter config is required

**Comment by sgdc3** [comment]
\+ there are severe maven inconsistencies in the child modules i need to look at them more in depth

**Comment by sgdc3** [comment]
Merging upstream, still a WIP, don't merge yet

**Comment by HoverEpic** [comment]
It's working standalone and the log is good looking? I have tested to implements slf4j yesterday but can't make it work properly in IDE and production environment.

**Comment by HoverEpic** [comment]
So i can merge?

**Comment by sgdc3** [comment]
Not yet, wait until tomorrow

**Comment by HoverEpic** [comment]
Ok

**Comment by sgdc3** [comment]
@HoverEpic Ready! :D

**Pull request merged**
