### PR TITLE
Make chunks actually render

### PR DESCRIPTION
**Pull request by Tim203**
This does not contain the correct block ids, just making the chunks actually render.
It contains some useless stuff, so use what you need ;p

### CODE REVIEW

**Comment by EOT3000** [comment]
ok, that works

**Comment by lukeeey** [comment]
This doesn't work on hypixel and makes me crash on mineplex.

**I tested on some random cracked servers as well**

skykingdoms.net:
image

mc.cosmicmc.net: crashes but i'm not sure if that was caused by this PR or not

**Comment by lukeeey** [comment]
Unless i'm doing something wrong with block ids?

**Comment by Tim203** [comment]
Atleast they render now 😂😛 (on some servers 😅)
I think I got more time to look at it on Tuesday or Wednesday.

**Comment by lukeeey** [comment]
ill merge it for now, hypixel looks like this currently 
image

**Comment by Tim203** [comment]
Wonderful isn't it? xd

**Pull request merged**
