### PR TITLE
MCPE server Experiment

### PR DESCRIPTION
**Pull request by Creeperface01**
Hi i think my code is bad but i tried to make mcpe connection but i dont know what packets should server send to connect to mcpe server

### CODE REVIEW

**Comment by Creeperface01** [comment]
Yes i removed some of your code for testing so you can not merge it but you can look at some classes

**Comment by TheDiamondYT1** [comment]
Use less commits... Like 1 or 2 instead of 10000000

**Comment by TheDiamondYT1** [comment]
Also we can do this in a new branch instead. I will create it soon.

**Comment by DefinitlyEvil** [comment]
Damn, that code looks crappy. Does it work anyways? 
We probably need to revert it, this won't work well.

**Comment by Creeperface01** [comment]
I dont know what packets should i send to mcpe server so it doesn't work because it sends loginpacket only

**Comment by Creeperface01** [comment]
I think it should Work Theoretically

**Comment by DefinitlyEvil** [comment]
Yeah but we should keep it in DEV branch instead of master one.

**Comment by Creeperface01** [comment]
Ok

**Comment by Creeperface01** [comment]
but can you told me how to connect to MCPE server? what packets should i send before login packet?

**Comment by TheDiamondYT1** [comment]
https://github.com/DragonetMC/DragonProxy/tree/dev

**Comment by TheDiamondYT1** [comment]
Push experimental features there and stable features to master

**Comment by Creeperface01** [comment]
ok

**Pull request closed without merging**
