### PR TITLE
Update player attributes when health is updated, fixes #123

### LINKED ISSUE #123: Taking more clientside damage and dieing clientside
After taking damage the client keeps showing that it's losing health until you die clientside, but not serverside. You can't respawn, until you die serverside.
http://tr7zw.de/u/1513019141.gif

### PR DESCRIPTION
**Pull request by johnnywoof**
The player's attributes are updated whenever the health is updated by the server. This means that the client will no longer take arbitrary damage. In addition, the player's food level will also be updated to the correct value too, instead of just remaining at a full level.
I also added a server difficulty translator. This will make sure that the client will no longer self-heal itself when connected to pc servers that are not on peaceful mode.

### CODE REVIEW

**Comment by lukeeey** [comment]
Please change the pull request title to say "Fix #123" so the issue will be automatically closed when this is merged

**Comment by lukeeey** [comment]
I'm on mobile so i cant

**Comment by lukeeey** [comment]
Sorry i mean youxan keep the old name, just add a comma then "fixes #123" after the comma

**Comment by DefinitlyEvil** [comment]
build faliure, pls fix?

**Comment by johnnywoof** [comment]
"fatal: Couldn't find remote ref refs/pull/176/merge"
Looks like I deleted the branch too early, oops. I think it can be ignored, since the main repo seems to [build correctly](https://travis-ci.org/DragonetMC/DragonProxy/builds/323644581).

**Comment by DefinitlyEvil** [comment]
kk

**Pull request merged**
