### PR TITLE
Move the MOTD configuration to the config file.

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
You can use '&' to colorize the MOTD.

The style of the MOTD is set as the same as before, but I added a "&a" to show the color functions.

You can use "%ip%" and "%port%" to show the PC server IP and Port.

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
Make a PR to the translation repo removing it from all the files

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy ok, doing this right now. :+1:

**Comment by RandomAltThingy** [comment]
MinecraftAPI.com is gone? Shit lmao

**Comment by MrPowerGamerBR** [comment]
Done: https://github.com/DragonetMC/DragonProxy-Translations/pull/6

**Pull request merged**
